name: Test

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: All on ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Ubuntu 22.04"
            os: "ubuntu-22.04"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build tests
        run: cargo test --workspace --no-run
      - name: Run tests
        run: cargo test --workspace --no-fail-fast
